### PR TITLE
One entry per date

### PR DESCRIPTION
**Pull request by r-meissner**
Made some changes to the AddEntryModal component and also App.jsx to pass props to it.

On entering the date while making a new entry, it now alerts you if you choose a date that already has an entry.

### CODE REVIEW

**Comment by r-meissner** [comment]
Realised I also need to change the EditEntryModal. Will reopen this once I am done.

**Comment by HOB3R** [comment]
OK :)

**Comment by r-meissner** [comment]
Made some changes to EditEntryModal component and to App.jsx to pass props.

It now alerts you when you try to save your edit if it matches the date of a different, already created entry.

**Comment by HOB3R** [comment]
Cool, you're really quick! It works perfectly! Feel free to merge 👍

**Pull request merged**
